version: '3.8'

services:
  # DB PostgreSQL
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/pg:/var/lib/postgresql/data

  # Redis
  redis:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./data/redis:/bitnami/redis/data
